LOGIN_REQUIRED = "LOGIN_REQUIRED"
WAITING_HUMAN_VERIFICATION = "WAITING_HUMAN_VERIFICATION"
PROFILE_START_FAILED = "PROFILE_START_FAILED"
DRIVER_CONNECT_FAILED = "DRIVER_CONNECT_FAILED"
IMAGE_DOWNLOAD_FAILED = "IMAGE_DOWNLOAD_FAILED"
IMAGE_UPLOAD_FAILED = "IMAGE_UPLOAD_FAILED"
SCREENSHOT_FAILED = "SCREENSHOT_FAILED"
ELEMENT_NOT_FOUND = "ELEMENT_NOT_FOUND"
CONTENT_REJECTED = "CONTENT_REJECTED"
SUBMIT_FAILED = "SUBMIT_FAILED"
NOTE_URL_NOT_FOUND = "NOTE_URL_NOT_FOUND"
ACCOUNT_RESTRICTED = "ACCOUNT_RESTRICTED"
EVIDENCE_NOT_FOUND = "EVIDENCE_NOT_FOUND"
EVIDENCE_JSON_INVALID = "EVIDENCE_JSON_INVALID"
YINGDAO_CONFIG_ERROR = "YINGDAO_CONFIG_ERROR"
YINGDAO_JOB_FAILED = "YINGDAO_JOB_FAILED"
YINGDAO_JOB_TIMEOUT = "YINGDAO_JOB_TIMEOUT"
KJVS_CONFIG_ERROR = "KJVS_CONFIG_ERROR"
KJVS_PROFILE_NOT_FOUND = "KJVS_PROFILE_NOT_FOUND"
KJVS_OPEN_FAILED = "KJVS_OPEN_FAILED"
KJVS_ENV_TIMEOUT = "KJVS_ENV_TIMEOUT"
KJVS_ENV_FAILED = "KJVS_ENV_FAILED"
KJVS_YINGDAO_PROVIDER_ERROR = "KJVS_YINGDAO_PROVIDER_ERROR"
RPA_DRY_RUN_FAILED = "RPA_DRY_RUN_FAILED"
RPA_DRY_RUN_CONFIG_ERROR = "RPA_DRY_RUN_CONFIG_ERROR"
RPA_DRY_RUN_PROFILE_MAP_NOT_FOUND = "RPA_DRY_RUN_PROFILE_MAP_NOT_FOUND"
RPA_DRY_RUN_ACCOUNT_NOT_FOUND = "RPA_DRY_RUN_ACCOUNT_NOT_FOUND"
RPA_DRY_RUN_EVIDENCE_DIR_ERROR = "RPA_DRY_RUN_EVIDENCE_DIR_ERROR"
UNKNOWN_ERROR = "UNKNOWN_ERROR"


class WorkerError(Exception):
    """Structured browser-worker error."""

    def __init__(
        self,
        error_code: str,
        error_message: str,
        retryable: bool = False,
    ) -> None:
        """Create a worker error."""
        self.error_code = error_code
        self.error_message = error_message
        self.retryable = retryable
        super().__init__(error_message)
